package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Emerald Palette (Default Islamic theme)
val EmeraldBgDark = Color(0xFF042116)
val EmeraldSurfaceDark = Color(0xFF0A3324)
val EmeraldSurfaceVariantDark = Color(0xFF104330)
val EmeraldPrimaryDark = Color(0xFF10B981)
val EmeraldAccentGold = Color(0xFFEAB308)
val EmeraldGoldLight = Color(0xFFFDE68A)
val EmeraldTextDark = Color(0xFFF0FDF4)
val EmeraldTextSecondaryDark = Color(0xFFA7F3D0)

val EmeraldBgLight = Color(0xFFF4FBF7)
val EmeraldSurfaceLight = Color(0xFFFFFFFF)
val EmeraldSurfaceVariantLight = Color(0xFFE6F4ED)
val EmeraldPrimaryLight = Color(0xFF047857)
val EmeraldTextLight = Color(0xFF064E3B)
val EmeraldTextSecondaryLight = Color(0xFF047857)

// Midnight Palette (Deep navy & soft teal)
val MidnightBg = Color(0xFF070D1B)
val MidnightSurface = Color(0xFF0E1830)
val MidnightSurfaceVariant = Color(0xFF16254A)
val MidnightPrimary = Color(0xFF38BDF8)
val MidnightSecondary = Color(0xFF2DD4BF)
val MidnightAccentGold = Color(0xFFF59E0B)
val MidnightText = Color(0xFFF0F9FF)
val MidnightTextSecondary = Color(0xFF94A3B8)

// Sand Palette (Warm parchment & olive bronze)
val SandBg = Color(0xFFF7F3EB)
val SandSurface = Color(0xFFFFFFFF)
val SandSurfaceVariant = Color(0xFFEFE8DB)
val SandPrimary = Color(0xFF78592B)
val SandSecondary = Color(0xFF536B4F)
val SandAccent = Color(0xFFB45309)
val SandText = Color(0xFF292524)
val SandTextSecondary = Color(0xFF78716C)

// Night Palette (OLED Black, deep emerald & muted gold)
val NightBg = Color(0xFF000000)
val NightSurface = Color(0xFF0F1412)
val NightSurfaceVariant = Color(0xFF18221D)
val NightPrimary = Color(0xFF22C55E)
val NightSecondary = Color(0xFF15803D)
val NightAccentGold = Color(0xFFCA8A04)
val NightText = Color(0xFFF9FAFB)
val NightTextSecondary = Color(0xFF9CA3AF)

// Rose Gold Palette (Deep plum & shimmering rose gold)
val RoseGoldBg = Color(0xFF1F1118)
val RoseGoldSurface = Color(0xFF2E1724)
val RoseGoldSurfaceVariant = Color(0xFF3F2133)
val RoseGoldPrimary = Color(0xFFF472B6)
val RoseGoldSecondary = Color(0xFFFB7185)
val RoseGoldAccent = Color(0xFFFBBF24)
val RoseGoldText = Color(0xFFFFF1F2)
val RoseGoldTextSecondary = Color(0xFFFDA4AF)

// Royal Amber Palette (Rich obsidian & radiant warm amber)
val RoyalAmberBg = Color(0xFF181007)
val RoyalAmberSurface = Color(0xFF281C0D)
val RoyalAmberSurfaceVariant = Color(0xFF3A2914)
val RoyalAmberPrimary = Color(0xFFF59E0B)
val RoyalAmberSecondary = Color(0xFFD97706)
val RoyalAmberAccent = Color(0xFFFBBF24)
val RoyalAmberText = Color(0xFFFEF3C7)
val RoyalAmberTextSecondary = Color(0xFFFCD34D)
